In [1]:
# downloading dataset for the customer churn predictions

import kagglehub
import shutil
import os

path = kagglehub.dataset_download("dhrubangtalukdar/telco-customer-churn-data")

destination = "../data"
os.makedirs(destination, exist_ok=True)

for file in os.listdir(path):
    shutil.copy(os.path.join(path, file), destination)

print("Copied to:", os.path.abspath(destination))

Copied to: /home/rohit/projects/customer_churn/data

* **Exploration Begins**

In [2]:
# eda 

import pandas as pd 
import numpy as np

In [3]:
data = pd.read_csv('../data/synthetic_customer_churn_100k.csv')
df = data
df.shape

(100000, 9)

In [4]:
df.head(10)

,CustomerID,Age,Gender,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn
0,1,56,Female,68,147.58,Two year,Bank transfer,10052.03,No
1,2,69,Male,32,22.54,Month-to-month,Mailed check,686.78,No
2,3,46,Female,10,52.47,One year,Electronic check,537.88,No
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
4,5,60,Female,54,130.98,Month-to-month,Credit card,7081.28,No
5,6,25,Female,29,111.55,Month-to-month,Credit card,3167.13,Yes
6,7,78,Female,20,63.23,One year,Electronic check,1307.22,No
7,8,38,Male,11,96.63,Month-to-month,Bank transfer,1093.32,Yes
8,9,56,Male,43,74.06,Month-to-month,Mailed check,3230.58,Yes
9,10,75,Other,62,109.39,One year,Electronic check,6799.64,No

In [5]:
df[df.Churn=='Yes']

,CustomerID,Age,Gender,Tenure,MonthlyCharges,Contract,PaymentMethod,TotalCharges,Churn
3,4,32,Male,22,109.67,Month-to-month,Mailed check,2390.04,Yes
5,6,25,Female,29,111.55,Month-to-month,Credit card,3167.13,Yes
7,8,38,Male,11,96.63,Month-to-month,Bank transfer,1093.32,Yes
8,9,56,Male,43,74.06,Month-to-month,Mailed check,3230.58,Yes
13,14,28,Female,17,121.38,Month-to-month,Mailed check,2061.90,Yes
...,...,...,...,...,...,...,...,...,...
99982,99983,35,Male,44,79.51,Month-to-month,Mailed check,3567.54,Yes
99983,99984,55,Female,50,12.78,Month-to-month,Mailed check,553.31,Yes
99989,99990,78,Female,50,94.66,Month-to-month,Electronic check,4765.99,Yes
99992,99993,61,Female,72,59.74,Month-to-month,Electronic check,4268.59,Yes
99997,99998,48,Other,32,75.37,Month-to-month,Credit card,2372.33,Yes

In [6]:
df.dtypes

CustomerID          int64
Age                 int64
Gender             object
Tenure              int64
MonthlyCharges    float64
Contract           object
PaymentMethod      object
TotalCharges      float64
Churn              object
dtype: object

In [7]:

df.isna().sum()

CustomerID        0
Age               0
Gender            0
Tenure            0
MonthlyCharges    0
Contract          0
PaymentMethod     0
TotalCharges      0
Churn             0
dtype: int64

In [8]:
df['Churn'].value_counts(normalize=False)

Churn
No     66856
Yes    33144
Name: count, dtype: int64

In [9]:
pd.crosstab(df['Contract'], df['Churn'], normalize='index')

Churn                 No       Yes
Contract
Month-to-month  0.534426  0.465574
One year        0.832509  0.167491
Two year        0.831215  0.168785

In [10]:
pd.crosstab(df['MonthlyCharges'], df['Churn'], normalize='index')

Churn                 No       Yes
MonthlyCharges
10.00           0.714286  0.285714
10.01           0.800000  0.200000
10.02           0.666667  0.333333
10.03           0.714286  0.285714
10.04           0.800000  0.200000
...                  ...       ...
149.96          0.400000  0.600000
149.97          0.333333  0.666667
149.98          0.166667  0.833333
149.99          0.333333  0.666667
150.00          0.200000  0.800000

[13990 rows x 2 columns]

In [11]:
df.groupby('Churn')['MonthlyCharges'].mean()

Churn
No     72.845838
Yes    94.355298
Name: MonthlyCharges, dtype: float64

In [12]:
df.groupby('Churn')['Tenure'].mean()

Churn
No     39.321796
Yes    30.889784
Name: Tenure, dtype: float64

*the following are the most important features* 
* Age 
* Gender
* Tenure
* MonthlyCharges
* Contract
* TotalCharges
* Churn

In [16]:
## splitting dataset into parts features (X) --> target (Y)


x = df.drop('Churn', axis=1)
y = df['Churn'].map({'Yes':1 , 'No':0})

print(x.head(10))
print(y.head(10))

   CustomerID  Age  Gender  Tenure  MonthlyCharges        Contract  \
0           1   56  Female      68          147.58        Two year
1           2   69    Male      32           22.54  Month-to-month
2           3   46  Female      10           52.47        One year
3           4   32    Male      22          109.67  Month-to-month
4           5   60  Female      54          130.98  Month-to-month
5           6   25  Female      29          111.55  Month-to-month
6           7   78  Female      20           63.23        One year
7           8   38    Male      11           96.63  Month-to-month
8           9   56    Male      43           74.06  Month-to-month
9          10   75   Other      62          109.39        One year

      PaymentMethod  TotalCharges
0     Bank transfer      10052.03
1      Mailed check        686.78
2  Electronic check        537.88
3      Mailed check       2390.04
4       Credit card       7081.28
5       Credit card       3167.13
6  Electronic check       1307.22
7     Bank transfer       1093.32
8      Mailed check       3230.58
9  Electronic check       6799.64
0    0
1    0
2    0
3    1
4    0
5    1
6    0
7    1
8    1
9    0
Name: Churn, dtype: int64

In [ ]:
# separating data into parts numerical and categorical features  

categorical_feat = x.select_dtypes(include=['object']).columns
numeric_feat = x.select_dtypes(include=['float','int64']).columns

print(categorical_feat)
print(numeric_feat)

Index(['Gender', 'Contract', 'PaymentMethod'], dtype='object')
Index(['CustomerID', 'Age', 'Tenure', 'MonthlyCharges', 'TotalCharges'], dtype='object')